### ISSUE TITLE
Why not consider a bit different approach?

### ISSUE THREAD

**Issue by bagobor** [dfranx/ShaderDebugger#1]
Similar work was done here: https://github.com/burg/glsl-simulator
it's easy to add simple JS VM and run it internally.

**Comment by dfranx** [comment]
Thanks for the suggestion!

Well, I can think of couple reasons:
 - it will be easy to expand this library to support HLSL (or any other language)
 - I feel like this way other programmers will be able to integrate ShaderDebugger more easily into their own projects
 - I know this might not be good, but: it uses my libraries which I find easy to modify and use. I currently don't have time for learning how glsl-simulator works internally, some JS VM library, etc...
 - and honestly, developing this library is so much fun

PS: Thank you so much for all those pull request. I will have a look at them presumably this weekend.

**Comment by bagobor** [comment]
Fun is fun :) 
OK
