### ISSUE TITLE
similarities and opportunities with valentingalea/vml

### ISSUE THREAD

**Issue by valentingalea** [dfranx/ShaderDebugger#4]
Hi,

this looks like a cool project and not too dissimilar with mine https://github.com/valentingalea/vml

I wonder if there's some opportunity for cross-pollination - for example I saw you use `glm` which in my view is too slow for debugging purposes. My library is no way near the stability of glm but still I wonder if it can be used instead.

Feel free to close this issue if you want as it's not a real indication of any problem.

Cheers,
Valentin

**Comment by dfranx** [comment]
Hey! Your library is very cool!
I haven't had a problem with glm speed when debugging, honestly. It is also stable, which is kind of important for ShaderDebugger. So I don't have plans to switch from glm anytime soon, sorry.
But as I said, your library is cool. I'll put it in some kind of "similar projects" section in the README file.
